package com.danimaniarqsoft.report.charts.dsl;

public enum ChartType {
	BAR_CHART, LINE_CHART, XY_PLOT_CHART, PIE_CHART, TIME_SERIES_CHART, HISTOGRAM_CHART, AREA_CHART, DIFFERENCE_CHART, STEP_CHART, GANTT_CHART, MULTIPLE_AXIS_CHART, COMBINED_OVERLAID_CHART
}
